### ISSUE TITLE
一些细节和性能问题

### ISSUE THREAD

**Issue by ZJUSaltFish** [abcyzj/MeshRet#2]
感谢大佬的工作！
想问一下MeshRet的性能如何？比如GPU帧率？

**Comment by ZJUSaltFish** [comment]
以及另一个问题：您在文章里写的选取KxL个点对的方法，其中L/2个近邻点和L/2个远点，是每一帧都要重新选取，还是在TPose选好后对整个动画保持不变？

**Comment by abcyzj** [comment]
在我们自己的硬件上测试，能跑到30FPS以上。选取点对是每一帧都要重新选的。

**Comment by ZJUSaltFish** [comment]
多谢!
